services:
    app:
        build:
            context: .
            dockerfile: DockerfileProd
        container_name: laravel_app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=database
            - DB_USERNAME=user
            - DB_PASSWORD=password
        working_dir: /var/www
        command: php-fpm
        networks:
            - app_network

    db:
        image: mysql:8.0.40
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - app_network

    nginx:
        image: nginx:stable
        container_name: nginx
        depends_on:
            - app
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - app_network

volumes:
    db_data:
    redis_data:

networks:
    app_network:
        driver: bridge
