services:
    app:
        build:
            context: .
            dockerfile: DockerfileDev
        container_name: laravel_app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=database
            - DB_USERNAME=user
            - DB_PASSWORD=password
        working_dir: /var/www
        command: >
          sh -c "composer install --no-dev --no-interaction --prefer-dist &&
                 php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.0.40
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    db_data:
    redis_data:
